### ISSUE TITLE
No TOC on Kindle?

### ISSUE THREAD

**Issue by tallforasmurf** [standardebooks/p-g-wodehouse_something-new#1]
Altho I see a toc.xhtml, when I open it in Kindle the "table of contents" entry in the "Go" menu is grayed out. Paging forward from the cover is just half-title, colophon, then chapter 1.

Don't know if that's a problem?

Edit: this is Kindle for Mac, not a "real" kindle!

**Comment by acabal** [comment]
Hi there,

1. What Kindle device and software version are you using?

2. Which file did you download from Standard Ebooks?

3. How did you get the file on to Kindle?

**Comment by tallforasmurf** [comment]
Opened https://standardebooks.org/ebooks/p-g-wodehouse/something-new/ in Firefox. Clicked on the azw3 link; Firefox helpfully offers to "open with Kindle (default app)" and it does. Kindle for Mac v 1.20.3 (47097) (the latest version, updated recently from the App Store) then opens the file to page 1. I use left-arrow to back up to the cover and note, hmph, no TOC? and pull down "Go" menu to observe that the "Table of Contents" menu choice is grayed out.

**Comment by acabal** [comment]
Thanks. Does this occur with other Standard Ebooks azw3 files?

**Comment by tallforasmurf** [comment]
I just tried Collins, The Woman in White and Thackeray, Vanity Fair, and yes, neither has access to a TOC.

**Comment by acabal** [comment]
In that case I think you should try using the compatible .epub file instead. You can try emailing it to yourself and hopefully Amazon will do some sort of half-decent job at converting it.

Amazon has different renders for different versions of their app on different platforms and thus it's nearly impossible to make one Kindle file that works the same way on every Kindle. Right now our azw3 files work best on the Kindle eInk devices and not necessarily the various Kindle apps Amazon has vomited out.

The best answer would be to switch to better ereading software, as Kindle is garbage and actively anti-ebook-developer. But I understand people buy in to their ecosystem so that's not always possible.

**Comment by tallforasmurf** [comment]
I downloaded Calibre v3.8 and opened the epub file. It also has no TOC, goes from Title page, colophon, chapter 1. (Also no cover image that I can see but I'm not familiar with Calibre's UI so maybe there's a "cover" button I didn't click.)

**Comment by acabal** [comment]
There's no ToC inline with the text; the idea is you use your ereading software's ToC functionality to access it, thus it's not necessary to be inline.

**Comment by tallforasmurf** [comment]
Correct, Calibre has an "open the TOC" button which does show the chapters as  roman numerals and jumps the them on clicking.

Hah! Looking at the Kindle UI, it also has a similar TOC button which opens a TOC as a separate list.

What confused me was that all the other books I have on my Kindle (99% from Amazon) have actual TOC pages which fall between the title page and the text. I am accustomed to using the Go menu to jump to the TOC **as a page** and from there to a chapter/story. Prior to this I had never clicked the button in the left tool-bar. However having seen how Calibre did it, I thought to have a look at the Kindle and there that was.

So there IS a TOC, and correctly presented, using the special TOC user interface widget. It remains the case that the Table of Contents menu item in the Go menu is grayed out.

Aaaaanyway, I will close this. Just be aware of these two different user interfaces to the TOC.

**Comment by acabal** [comment]
Glad to hear you got it sorted out. Thanks!
