### ISSUE TITLE
Cover image is missing title

### ISSUE THREAD

**Issue by raphaeldore** [standardebooks/p-g-wodehouse_something-new#2]
Hi,

I noticed that the cover image is missing the title of the book. Here is the current cover:

![cover with no title](https://standardebooks.org/ebooks/p-g-wodehouse/something-new/dist/thumbnail_d04a1e906bc9e8eedab44ddd539412217058e02a_EBOK_portrait.jpg)

I investigated a little bit, and found that the issue came with commit a8a5e182b5ea80bc75d1e3e8cad1a2002ae44a6d, because the cover was fine before that: https://github.com/standardebooks/p-g-wodehouse_something-new/blob/3be32d7fdb4a00f332588bb52386911aab0b7072/src/epub/images/cover.svg

Just wanted to let you know!

-Raphaël

**Comment by acabal** [comment]
Thanks, this should be fixed now!

**Comment by raphaeldore** [comment]
That was fast! Thanks.
